"""working post assign functionality

Revision ID: 1af1f5f9db9a
Revises: 9ba87e038103
Create Date: 2024-05-10 01:10:34.897494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1af1f5f9db9a'
down_revision = '9ba87e038103'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_user_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_posts_assigned_user_id'), ['assigned_user_id'], unique=False)
        batch_op.create_foreign_key('fk_assigned_user_id', 'users', ['assigned_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_assigned_user_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_posts_assigned_user_id'))
        batch_op.drop_column('assigned_user_id')

    # ### end Alembic commands ###
