"""new fields

Revision ID: 9ba87e038103
Revises: e6dc4614ebc6
Create Date: 2024-05-09 23:50:01.594793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ba87e038103'
down_revision = 'e6dc4614ebc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned', sa.Boolean(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('account_created', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('account_created')
        batch_op.drop_column('about')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('assigned')

    # ### end Alembic commands ###
